### ISSUE TITLE
Unable to parse sample names from Mutect2 

### ISSUE THREAD

**Issue by jfnavarro** [umich-brcf-bioinf/Jacquard#4]
Hi,

It seems like `jacquard translate` is not able to parse Mutect2 VCFs (v2.2) or it is
expecting the normal and tumor samples to have a specific name? The VCF that
I got from Mutect2 does not have a `##SAMPLE=<ID=..` field and the sample names
are preceded by `##normal_sample=..` and `##tumor_sample=..`. 

Is it an issue of the version that I am using or is there a workaround for this? 

The error message that I get is:

` "Unable to determine normal "
jacquard.utils.utils.JQException: Unable to determine normal and tumor sample ordering based on MuTect metaheader.`

**Comment by cgates** [comment]
Hi,
Thanks for your interest in Jacquard. I suspect this is a bug in Jacquard. Would you be willing to share an excerpt of the VCF metaheader block? If you ran this:
`grep '^#' your_vcf.vcf | grep -v 'contig' > tmp.vcf`
and posted the content of tmp.vcf here or emailed them to bfx-jacquard@umich.edu, we would be happy to investigate.
Best,
cg

**Comment by jfnavarro** [comment]
Hi! 

Thanks for your quick answer. 

I've just emailed you the header of the VCF as requested. 

As you can see there is no `##SAMPLE=` tag, the sample names are preceded
by `##nromal_sample=` and `#tumor_sample=` and there is no `--tumor-sample` parameter
in the `##GATKCommandLine=` tag and this is because this parameter is now deprecated 
(I believe I am using the latest version of Mutect2). I took a look to `/variant_caller_transforms/mutect.py`
and I believe these things may be related to the bug. I like how you wrote and structured the code by the way! 

Best,
Jose

**Comment by cgates** [comment]
Hi Jose,

I received the file. I'll try to sort this out by Friday.

Best,
cg

**Comment by cgates** [comment]
Hi Jose,
I believe the version released today (1.1.5) will correctly handle your metaheaders. Give it a try and let me know if you have questions.
Best,
cg

**Comment by jfnavarro** [comment]
Hi Chris, 

I texted it and it worked flawlessly, thanks!! 

Best,
Jose

**Comment by cgates** [comment]
Outstanding. Thanks!
